# Generated by Django 5.0.4 on 2024-04-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_alter_category_slug_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='reated_date',
            new_name='created_date',
        ),
    ]
