# Generated by Django 5.0.4 on 2024-04-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_rename_reated_date_slider_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='created_date',
            new_name='create_date',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='banner',
        ),
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(default='', upload_to='pictute'),
        ),
    ]
