# Generated by Django 5.0.4 on 2024-04-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
