# Generated by Django 5.0.4 on 2024-04-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_create_date_coupon_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='required_amount_to_use_coupo',
            field=models.PositiveBigIntegerField(default=100),
            preserve_default=False,
        ),
    ]
