# Generated by Django 5.0.4 on 2024-04-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_coupon_required_amount_to_use_coupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='required_amount_to_use_coupo',
            new_name='required_amount_to_use_coupon',
        ),
    ]
